// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksAPI.Models;

namespace ProjectAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191101162854_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("ParkName");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "The Molalla River State Park is located in U.S. state of Oregon. It is a few miles north of Canby, and half a mile from the Canby Ferry. The park is south of the Willamette River and east of the Molalla River, at the confluence of the Pudding, Molalla and Willamette rivers.",
                            Location = "Canby, OR 97013",
                            ParkName = "Molalla River State Park"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "A popular campground and day-use area, Cape Lookout is located on a sand spit between Netarts Bay and the ocean, giving you a terrific view of the ocean with convenient access to the beach. Note: The beach at Cape Lookout is protected by a 50' wide cobble-sized stone revetment. The revetment helps prevent erosion and stabilizes the man-made dune that protects the campground. Visitors that wish to access the beach must walk through the revetment. Please be careful when on the cobble stones, as they can be unstable.",
                            Location = "45.36682,-123.962148",
                            ParkName = "Cape Lookout State Park"
                        });
                });

            modelBuilder.Entity("ParksAPI.Models.Trail", b =>
                {
                    b.Property<int>("TrailId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChallengeRating");

                    b.Property<double>("Length");

                    b.Property<int>("ParkId");

                    b.Property<string>("TrailName");

                    b.HasKey("TrailId");

                    b.HasIndex("ParkId");

                    b.ToTable("Trails");

                    b.HasData(
                        new
                        {
                            TrailId = 1,
                            ChallengeRating = 2,
                            Length = 5.0,
                            ParkId = 1,
                            TrailName = "Easy River Run"
                        },
                        new
                        {
                            TrailId = 2,
                            ChallengeRating = 4,
                            Length = 2.3999999999999999,
                            ParkId = 2,
                            TrailName = "Cape Lookout Trail"
                        },
                        new
                        {
                            TrailId = 3,
                            ChallengeRating = 1,
                            Length = 1.7,
                            ParkId = 2,
                            TrailName = "The Nature Trail"
                        },
                        new
                        {
                            TrailId = 4,
                            ChallengeRating = 5,
                            Length = 17.0,
                            ParkId = 2,
                            TrailName = "Cape Trail Heights"
                        });
                });

            modelBuilder.Entity("ParksAPI.Models.Trail", b =>
                {
                    b.HasOne("ParksAPI.Models.Park")
                        .WithMany("Trails")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
